---
title: "covariateScaling_chunk"
output: html_document
---


```{r echo=FALSE,results='hide'}
library(mcdocs)

```


`r opt("Covariates conditioning")` rules how the model is conditioned to different values of the continuous independent variables in the _simple effects_ estimation and in the _plots_ when there is an interaction in the model.

* `r opt("Mean+SD")`: means that the IV is conditioned to the $mean$,  to $mean+k \cdot sd$, and to  $mean-k\cdot sd$, where $k$ is ruled by the white field below the option. Default is 1 SD.

* `r opt("Percentile 50 +offset")`: means that the IV is conditioned to the $median$, the  $median+k P$, and the $median-k\cdot P$, where $P$ is the offset of percentile one needs. Again, the $P$ is ruled by the white field below the option. Default is 25%. The default conditions the model to: 

    + $50^{th}-25^{th}=25^{th}$ percentile
    
    + $50^{th}$ percentile 
    
    + $50^{th}+25^{th}=75^{th}$ percentile 

The offset should be within 5 and 50.

Note that with either of these two options, one can estimate simple effects and plots for any value of the continuous IV.

`r opt("Covariates labeling")` decides which label should be associated with the estimates and plots of simple effects as follows:

* `r opt("Labels")` produces strings of the form $Mean \pm SD$

* `r opt("Values")` uses the actual values of the variables

* `r opt("Labels+Values")` produces labels of the form $Mean \pm SD=XXXX$, where `XXXX` is the actual value.

* `r opt("Unscaled Values")` produces labels indicating the actual value (of the mean and sd) of the orginal variable scale. This can be useful, for instance, when the user need the estimates to be obtained with centered variables (because there are interactions, for instance), but the plot of the effects is preferred in the orginal scales.

* `r opt("Unscaled Values + Labels")` as the previous option, but add also the label "Mean" and "SD" to the orginal values.

The `r opt("Scaling on")` option decides how the scaling of the variables handle missing values: First, keep in mind that the model will be estimated on complete cases, no matter how this option is set. When there are missing values, however, one can scale each variable only on the complete cases (the default), or scale `columnwise`. If `columnwise` is selected, the mean and standard deviation of each variable used to scale the scores are computed with the available data of the variable, independently of possible missing values in other variables.

