---
title: "factorcoding_chunk"
output: html_document
---


```{r echo=FALSE,results='hide'}
library(mcdocs)
mcdocs_init()
```


It allows to code the categorical variables according to different coding schemas. The coding schema applies to all parameters estimates. The default coding schema is `r opt("simple")`, which is centered to zero and compares each means with the reference category mean. The reference category is the first appearing in the variable levels. 

Note that all contrasts but `r opt("dummy")` guarantee to be centered to zero (intercept being the grand mean), so when involved in interactions the other variables coefficients can be interpret as (main) average effects. If contrast `r opt("dummy")` is set, the intercept and the effects of other variables in interactions are estimated for the first group of the categorical IV.  

Contrasts definitions are provided in the estimates table. More detailed definitions of the comparisons operated by the contrasts can be obtained by selecting `r opt("Show contrast definition table")`. 

Differently to standard R naming system, contrasts variables are always named with the name of the factor and progressive numbers from 1 to K-1, where K is the number of levels of the factor.

In reading the contrast labels, one should interpret the `(1,2,3)` code as meaning "the mean of the levels 1,2, and 3 pooled toghether". If factor levels 1,2 and 3 are all levels of the factor in the samples, `(1,2,3)` is equivalent to "the mean of the sample". For example, for a three levels factor, a contrast labeled `1-(1,2,3)` means that the contrast is comparing the mean of level 1 against the mean of the sample. For the same factor, a contrast labeled `1-(2,3)` indicates a comparison between level 1 mean and the subsequent levels means pooled together.

