---
title: "GAMLj in R"
topic: r
category: help
output: 
  html_document:
     includes:
         in_header: ganalytics.txt
     toc: true
     toc_float:
        collapsed: true
editor_options: 
  chunk_output_type: console
---


```{r setup, echo=FALSE,results='hide'}
library(mcdocs)
mcdocs_init()

```

`r version("2.4.0")` 

## R help

<div class="bignote">  

`r modulename()` module can be installed and used in R as a standard R packages. Please check the R help for details. 

`r ext_url("R help and vignettees","rpackage/reference/")`

</div>

# Installation

At the moment, `r modulename()` is not in CRAN yet, so you need to install it via `devtools`

```{r, eval=FALSE}
devtools::install_github("gamlj/gamlj")
```

```{r, echo=FALSE,results='hide'}

# pkg<-"gamlj"
# fn<-NULL
# 
# extract_help<-function(pkg) {
#   rdbfile <- file.path(find.package(pkg), "help", pkg)
#   rdb <- tools:::fetchRdDB(rdbfile, key = fn)
#   convertor <- function(a) tools::Rd2HTML(a,fragment = F)
#   f <- function(x) {
#      if (length(Rdpack::Rdo_locate_core_section(rdo = x, sec = "\\value"))==0)
#         return(NULL)
#      good<-""
#      y<-fixRd(x)
#      res<-capture.output(convertor(y))
#      res<-res[8:(length(res)-1)]
#      for (a in res)
#         if(a!="")
#            good<-paste(good,a,"\n")
#     good
#   }
#   if(is.null(fn)) lapply(rdb, f) else f(rdb)
# }
# 
# 
# res<-extract_help(pkg) 

### this should be fixed in mcdocs
#for (r in seq_along(res))
#   if (!is.null(res[[r]]))
#         res[[r]]<-paste("<script>",res[[r]])

```

```{r, echo=FALSE,results='asis'}

# for (r in res)
#    cat(r)


```



`r issues()`
