<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="generator" content="pandoc" />

    
    
    <title>Rosetta store: contrasts</title>

        <script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
        <script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="site_libs/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet" />
        <script src="site_libs/bootstrap-3.3.7/js/bootstrap.min.js"></script>
        <script src="site_libs/navigation-1.1/tabsets.js"></script>
        <link href="site_libs/magnific-popup-1.1.0/magnific-popup.css" rel="stylesheet" />
        <script src="site_libs/magnific-popup-1.1.0/jquery.magnific-popup.min.js"></script>
        <link href="site_libs/readthedown-0.1/readthedown.css" rel="stylesheet" />
        <link href="site_libs/readthedown-0.1/readthedown_fonts_embed.css" rel="stylesheet" />
        <script src="site_libs/readthedown-0.1/readthedown.js"></script>
        <script>
        $(document).ready(function () {

            if ($(".root")[0]){
              return
            };
            $('.navbar-toggle').show();
            $('.navbar').css('display', 'none');
            $('#sidebar > h2 ').append("<a id='navbut' href=''><i class='fa fa-bars'></i></a>");
            $('#navbut').on( "click", function(e) {
                       $('.navbar').toggle();
                       e.preventDefault();
               } );
              $('.navbar-toggle').on('click', function(e) {
                       $('.navbar').toggle();
                       e.preventDefault();
              });       
            $(window).scroll(function (event) {
                $('.navbar').css('display', 'none');
            });       
        });
        </script>
        <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-KM7X6HK5HM"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-KM7X6HK5HM');
        </script>
    
    
        <style type="text/css">code{white-space: pre;}</style>
    <style type="text/css">
      pre > code.sourceCode { white-space: pre; position: relative; }
      pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
      pre > code.sourceCode > span:empty { height: 1.2em; }
      .sourceCode { overflow: visible; }
      code.sourceCode > span { color: inherit; text-decoration: inherit; }
      div.sourceCode { margin: 1em 0; }
      pre.sourceCode { margin: 0; }
      @media screen {
      div.sourceCode { overflow: auto; }
      }
      @media print {
      pre > code.sourceCode { white-space: pre-wrap; }
      pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
      }
      pre.numberSource code
        { counter-reset: source-line 0; }
      pre.numberSource code > span
        { position: relative; left: -4em; counter-increment: source-line; }
      pre.numberSource code > span > a:first-child::before
        { content: counter(source-line);
          position: relative; left: -1em; text-align: right; vertical-align: baseline;
          border: none; display: inline-block;
          -webkit-touch-callout: none; -webkit-user-select: none;
          -khtml-user-select: none; -moz-user-select: none;
          -ms-user-select: none; user-select: none;
          padding: 0 4px; width: 4em;
          background-color: #ffffff;
          color: #a0a0a0;
        }
      pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
      div.sourceCode
        { color: #1f1c1b; background-color: #ffffff; }
      @media screen {
      pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
      }
      code span { color: #1f1c1b; } /* Normal */
      code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
      code span.an { color: #ca60ca; } /* Annotation */
      code span.at { color: #0057ae; } /* Attribute */
      code span.bn { color: #b08000; } /* BaseN */
      code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
      code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
      code span.ch { color: #924c9d; } /* Char */
      code span.cn { color: #aa5500; } /* Constant */
      code span.co { color: #898887; } /* Comment */
      code span.cv { color: #0095ff; } /* CommentVar */
      code span.do { color: #607880; } /* Documentation */
      code span.dt { color: #0057ae; } /* DataType */
      code span.dv { color: #b08000; } /* DecVal */
      code span.er { color: #bf0303; text-decoration: underline; } /* Error */
      code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
      code span.fl { color: #b08000; } /* Float */
      code span.fu { color: #644a9b; } /* Function */
      code span.im { color: #ff5500; } /* Import */
      code span.in { color: #b08000; } /* Information */
      code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
      code span.op { color: #1f1c1b; } /* Operator */
      code span.ot { color: #006e28; } /* Other */
      code span.pp { color: #006e28; } /* Preprocessor */
      code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
      code span.sc { color: #3daee9; } /* SpecialChar */
      code span.ss { color: #ff5500; } /* SpecialString */
      code span.st { color: #bf0303; } /* String */
      code span.va { color: #0057ae; } /* Variable */
      code span.vs { color: #bf0303; } /* VerbatimString */
      code span.wa { color: #bf0303; } /* Warning */
    </style>
    
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" type="text/css" />
        <link rel="stylesheet" href="mcdocs.css" type="text/css" />
        <link rel="stylesheet" href="down.css" type="text/css" />
    
    <!-- tabsets -->
    <script>
      $(document).ready(function () {
	  window.buildTabsets("toc");
      });
      $(document).ready(function () {
	  $('.tabset-dropdown > .nav-tabs > li').click(function () {
	      $(this).parent().toggleClass('nav-tabs-open')
	  });
      });
    </script>

    <!-- code folding -->
    
    <!-- code download -->
    
    <!-- tabsets dropdown -->

    <style type="text/css">
      .tabset-dropdown > .nav-tabs {
	  display: inline-table;
	  max-height: 500px;
	  min-height: 44px;
	  overflow-y: auto;
	  background: white;
	  border: 1px solid #ddd;
	  border-radius: 4px;
      }
      
      .tabset-dropdown > .nav-tabs > li.active:before {
	  content: "";
	  font-family: 'Glyphicons Halflings';
	  display: inline-block;
	  padding: 10px;
	  border-right: 1px solid #ddd;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
	  content: "&#xe258;";
	  border: none;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
	  content: "";
	  font-family: 'Glyphicons Halflings';
	  display: inline-block;
	  padding: 10px;
	  border-right: 1px solid #ddd;
      }
      
      .tabset-dropdown > .nav-tabs > li.active {
	  display: block;
      }

      .tabset-dropdown > .nav-tabs > li.active a {
  	  padding: 0 15px !important;
      }

      .tabset-dropdown > .nav-tabs > li > a,
      .tabset-dropdown > .nav-tabs > li > a:focus,
      .tabset-dropdown > .nav-tabs > li > a:hover {
	  border: none;
	  display: inline-block;
	  border-radius: 4px;
	  background-color: transparent;
      }
      
      .tabset-dropdown > .nav-tabs.nav-tabs-open > li {
	  display: block;
	  float: none;
      }
      
      .tabset-dropdown > .nav-tabs > li {
	  display: none;
	  margin-left: 0 !important;
      }
    </style>
    
</head>

<body class="preload">

   	
         <!-- readthedown start -->   
   <div id="content" data-toggle="wy-nav-shift">
     <nav id="nav-top" role="navigation" aria-label="top navigation">
       <a role="button" href="#" data-toggle="wy-nav-top"><span class="glyphicon glyphicon-menu-hamburger"></span></a>
     </nav>
         
   
      
      <div class="navbar navbar-default  navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">GAMLj</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li>
        <a href="glm.html">GLM</a>
      </li>
      <li>
        <a href="mixed.html">Mixed</a>
      </li>
      <li>
        <a href="gzlm.html">Generalized</a>
      </li>
      <li>
        <a href="gzlmmixed.html">Generalized Mixed</a>
      </li>
      <li>
        <a href="examples.html">Examples</a>
      </li>
      <li>
        <a href="release_notes.html">Release notes</a>
      </li>
      <li>
        <a href="vignettes.html">GAMLj in R</a>
      </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
        <a href="https://github.com/gamlj/gamlj">View on Github</a>
      </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container -->
      </div><!--/.navbar -->
        
      <h1 class="title">Rosetta store: contrasts</h1>
      
         <!-- readthedown authors -->
   <div id="sidebar">
    <h2><a href="#content">Rosetta store: contrasts</a></h2>
    <div id="toc">
      <ul>
      <li><a href="#introduction"
      id="toc-introduction">Introduction</a></li>
      <li><a href="#software" id="toc-software">Software</a></li>
      <li><a href="#more-technical-details"
      id="toc-more-technical-details">More technical details</a></li>
      <li><a href="#terminology"
      id="toc-terminology">Terminology</a></li>
      <li><a href="#contrast-deviation"
      id="toc-contrast-deviation">Contrast: Deviation</a>
      <ul>
      <li><a href="#meaning" id="toc-meaning">Meaning</a></li>
      <li><a href="#jamovi-anova" id="toc-jamovi-anova"><span
      class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
      ANOVA</a></li>
      <li><a href="#jamovi-gamlj-glm" id="toc-jamovi-gamlj-glm"><span
      class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
      <span class="modulename">GAMLj</span> GLM</a></li>
      <li><a href="#spss" id="toc-spss">SPSS</a></li>
      <li><a href="#r" id="toc-r">R</a></li>
      <li><a href="#r-emmeans" id="toc-r-emmeans">R emmeans</a></li>
      </ul></li>
      <li><a href="#contrast-simple-dummy"
      id="toc-contrast-simple-dummy">Contrast: Simple &amp; Dummy</a>
      <ul>
      <li><a href="#meaning-1" id="toc-meaning-1">Meaning</a></li>
      <li><a href="#jamovi-anova-1" id="toc-jamovi-anova-1"><span
      class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
      ANOVA</a></li>
      <li><a href="#jamovi-gamlj-glm-1"
      id="toc-jamovi-gamlj-glm-1"><span
      class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
      <span class="modulename">GAMLj</span> GLM</a></li>
      <li><a href="#spss-1" id="toc-spss-1">SPSS</a></li>
      <li><a href="#r-1" id="toc-r-1">R</a></li>
      <li><a href="#r-emmeans-1" id="toc-r-emmeans-1">R emmeans</a></li>
      <li><a href="#simple-vs-dummy" id="toc-simple-vs-dummy">Simple vs
      Dummy</a></li>
      </ul></li>
      <li><a href="#contrast-repeated"
      id="toc-contrast-repeated">Contrast: Repeated</a>
      <ul>
      <li><a href="#jamovi-anova-2" id="toc-jamovi-anova-2"><span
      class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
      ANOVA</a></li>
      <li><a href="#jamovi-gamlj-glm-2"
      id="toc-jamovi-gamlj-glm-2"><span
      class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
      <span class="modulename">GAMLj</span> GLM</a></li>
      <li><a href="#spss-2" id="toc-spss-2">SPSS</a></li>
      <li><a href="#r-2" id="toc-r-2">R</a></li>
      <li><a href="#r-emmeans-2" id="toc-r-emmeans-2">R emmeans</a></li>
      </ul></li>
      <li><a href="#contrast-polynomial"
      id="toc-contrast-polynomial">Contrast: Polynomial</a>
      <ul>
      <li><a href="#jamovi-anova-3" id="toc-jamovi-anova-3"><span
      class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
      ANOVA</a></li>
      <li><a href="#jamovi-gamlj-glm-3"
      id="toc-jamovi-gamlj-glm-3"><span
      class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
      <span class="modulename">GAMLj</span> GLM</a></li>
      <li><a href="#spss-3" id="toc-spss-3">SPSS</a></li>
      <li><a href="#r-3" id="toc-r-3">R</a></li>
      <li><a href="#r-emmeans-3" id="toc-r-emmeans-3">R emmeans</a></li>
      </ul></li>
      <li><a href="#contrast-difference"
      id="toc-contrast-difference">Contrast: Difference</a>
      <ul>
      <li><a href="#jamovi-anova-4" id="toc-jamovi-anova-4"><span
      class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
      ANOVA</a></li>
      <li><a href="#jamovi-gamlj-glm-4"
      id="toc-jamovi-gamlj-glm-4"><span
      class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
      <span class="modulename">GAMLj</span> GLM</a></li>
      <li><a href="#spss-4" id="toc-spss-4">SPSS</a></li>
      <li><a href="#r-4" id="toc-r-4">R</a></li>
      <li><a href="#r-emmeans-4" id="toc-r-emmeans-4">R emmeans</a></li>
      </ul></li>
      <li><a href="#contrast-helmert"
      id="toc-contrast-helmert">Contrast: Helmert</a>
      <ul>
      <li><a href="#jamovi-anova-5" id="toc-jamovi-anova-5"><span
      class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
      ANOVA</a></li>
      <li><a href="#jamovi-gamlj-glm-5"
      id="toc-jamovi-gamlj-glm-5"><span
      class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
      <span class="modulename">GAMLj</span> GLM</a></li>
      <li><a href="#spss-5" id="toc-spss-5">SPSS</a></li>
      <li><a href="#r-5" id="toc-r-5">R</a></li>
      <li><a href="#r-emmeans-5" id="toc-r-emmeans-5">R emmeans</a></li>
      </ul></li>
      <li><a href="#contrast-matrix-vs-model-matrix"
      id="toc-contrast-matrix-vs-model-matrix">Contrast matrix vs model
      matrix</a>
      <ul>
      <li><a href="#building-custom-contrast-in-emmeans"
      id="toc-building-custom-contrast-in-emmeans">Building custom
      contrast in emmeans</a></li>
      </ul></li>
      <li><a href="#rosettas-files" id="toc-rosettas-files">Rosetta’s
      files</a></li>
      <li><a href="#comments" id="toc-comments">Comments?</a></li>
      </ul>
    </div>
    <div id="postamble" data-toggle="wy-nav-shift" class="status">
                </div>
   </div>
     

   
      
   
<!-- Don't indent these lines or it will mess pre blocks indentation --> 
<div id="main">
<p><span class="keywords"> <span class="keytitle"> keywords </span>
jamovi, SPSS, R, contrasts, comparisons, planned comparisons, LMATRIX,
contr.sum, emmeans </span></p>
<div class="version">
<p>
0.9.5
</p>
</div>
<div style="clear:both">

</div>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>Here you can find comparisons of results obtained in <span
class="modulename">GAMLj</span>, <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
(jmv), pure R, and SPSS. When not explicitely discussed, the code of
different software is written with the aim of obtaing identical results
across programs.</p>
<p>Example data are <a
href="https://github.com/gamlj/gamlj/blob/master/data/fivegroups.csv">here</a>
or in the <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
data library, under <code>General Analysis for Linear Models (3)</code>,
named <code>fivegroups</code>. One continuous dependent variable, one
factor with 4 groups.</p>
<p>Unfortunately, contrasts coding schemes get different names in
different publications and they are implemented in different ways across
software. Things can get a bit confusing because of this. For partially
overlapping coding scheme definitions see <a
href="https://stats.idre.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/">UCLA
idre web site</a>, <a
href="https://www.ibm.com/support/knowledgecenter/en/SSLVMB_20.0.0/com.ibm.spss.statistics.help/contrasts.htm">SPSS
manual</a> and <em>Cohen, J., Cohen, P., West, S. G., &amp; Aiken, L. S.
(2013). Applied multiple regression/correlation analysis for the
behavioral sciences. Routledge.</em> If you have familiarity with
python, you can compare results also with <a
href="http://www.statsmodels.org/dev/contrasts.html">python statmodels
results</a></p>
</div>
<div id="software" class="section level1">
<h1>Software</h1>
<p>We use <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>,
SPSS and R. In <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
we compare the ANOVA module in <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
<code>jmv</code> and the <span class="modulename">GAMLj</span> module.
In R we use <em>pure R</em>, meaning that we estimate the contrast
comparisons by estimating a linear model (<code>lm()</code> in
particular), with the categorical variable properly coded. For more
straigthforward estimation we employ <code>emmeans</code> R module. In
SPSS we use the <code>UNIVARIATE</code> module.</p>
</div>
<div id="more-technical-details" class="section level1">
<h1>More technical details</h1>
<p>Contrasts can be computed in two different ways:</p>
<ul>
<li><p>As the coefficients of a model where the categorical variable(s)
is coded accordingly to a coding scheme. <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
<span class="modulename">GAMLj</span> and standard R use this strategy.
Understanding this approach opens to the possibility to test
contrasts-based hypotheses in complex models, such as when interactions
are involved, mediatiated effects or simple effects are of
interest.</p></li>
<li><p>As a comparison between sets of means tested with model-derived
standard errors. <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
ANOVA, <code>emmeans</code> R and SPSS use this approach. This approach
is simpler and straightforward. In simple models, it works perfectly
fine.</p></li>
<li><p>As a comparison between groups means, with group specific
standard errors. None of the software used here uses this approach, so
we do not deal with it here.</p></li>
</ul>
<p>The first two approaches give the same results if the contrasts are
defined in the same way. However, the contrast coding displayed by the
software may be different. The majority of software prints out the
<strong>contrast matrix</strong>, which contains the coding scheme
describing the tested comparisons. R model estimation requires the
<strong>model matrix</strong>, which is generally different from the
contrast matrix and represents the weights associated with the dummy
variables needed to cast a categorical variable into the linear model
estimating the contrasts. How they are related and how to obtain one
from the other is explained in <a
href="#contrast_matrix_and_model_matrix_details">contrast vs model
matrix details</a></p>
<p>Furthermore, in simple models (such as one-way ANOVA), the two first
approaches give exactly the same results. When models get more complex,
results may diverge across software because they estimate different
things. <strong>The present results apply to one-way ANOVA, balanced
factorial ANOVA with centered coding scheme, ANCOVA models with
continuous covariates centered to their means</strong>.</p>
</div>
<div id="terminology" class="section level1">
<h1>Terminology</h1>
<p>To interpret a contrast, it is often necessary to refer to “the first
group” or “subsequent groups”. The order is always defined as the
alphanumeric order.</p>
<p>Furthermore, different software packages have different rounding
rules, so we say “the same results” when results agree apart for decimal
rounding.</p>
</div>
<div id="contrast-deviation" class="section level1">
<h1>Contrast: Deviation</h1>
<div id="meaning" class="section level2">
<h2>Meaning</h2>
<p><b>Definition: </b><i> Compares each group mean to the grand mean.
The grand mean is the mean of the groups means. The first group is
omitted</i></p>
</div>
<div id="jamovi-anova" class="section level2">
<h2><span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
ANOVA</h2>
<p><img src="rosetta/contrasts/c1.anova1.png" class="img-responsive" alt=""></p>
<p>Setting the contrasts to <code>deviation</code></p>
<p><img src="rosetta/contrasts/c1.anova2.png" class="img-responsive" alt=""></p>
<p>Results:</p>
<p><img src="rosetta/contrasts/r.c1.anova1.png" class="img-responsive" alt=""></p>
</div>
<div id="jamovi-gamlj-glm" class="section level2">
<h2><span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
<span class="modulename">GAMLj</span> GLM</h2>
<p><img src="rosetta/contrasts/c1.anova2.png" class="img-responsive" alt=""></p>
<p>Results:</p>
<p><img src="rosetta/contrasts/r.c1.gamlj1.png" class="img-responsive" alt=""></p>
<p>The expected means of the four groups are:</p>
<p><img src="rosetta/contrasts/r.c1.gamlj2.png" class="img-responsive" alt=""></p>
</div>
<div id="spss" class="section level2">
<h2>SPSS</h2>
<p>Please note that SPSS default sets the last group as reference group
(the omitted group), thus to obtain the same results as before, we
should set <code>/CONTRAST(Group)=Deviation(1)</code>, mind the “1”“,
which corresponds to”first” in the GUI options.</p>
<p><img src="rosetta/contrasts/c1.spss1.png" class="img-responsive" alt=""></p>
<pre><code>UNIANOVA Score BY Group
  /CONTRAST(Group)=Deviation(1)
  /METHOD=SSTYPE(3)
  /INTERCEPT=INCLUDE
  /PRINT=TEST(LMATRIX)
  /CRITERIA=ALPHA(.05)
  /DESIGN=Group.
</code></pre>
<p><img src="rosetta/contrasts/r.c1.spss1.png" class="img-responsive" alt=""></p>
</div>
<div id="r" class="section level2">
<h2>R</h2>
<p>In R, deviation contrast is called <code>contr.sum</code>. The
function defaults to omitting the last group, so we reverse it to omit
the first.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a>file<span class="ot">&lt;-</span><span class="st">&quot;../data/rosetta.contrasts.csv&quot;</span></span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read.csv2</span>(file,<span class="at">stringsAsFactors =</span> F)</span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a>dat<span class="sc">$</span>Group<span class="ot">&lt;-</span><span class="fu">factor</span>(dat<span class="sc">$</span>Group)</span>
<span id="cb2-4"><a href="#cb2-4" tabindex="-1"></a>dat<span class="sc">$</span>Score<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(dat<span class="sc">$</span>Score)</span>
<span id="cb2-5"><a href="#cb2-5" tabindex="-1"></a><span class="do">### reverse contrast sum </span><span class="al">###</span></span>
<span id="cb2-6"><a href="#cb2-6" tabindex="-1"></a><span class="fu">contrasts</span>(dat<span class="sc">$</span>Group)<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">rev</span>(<span class="fu">contr.sum</span>(<span class="dv">4</span>)),<span class="at">ncol=</span><span class="dv">3</span>)</span>
<span id="cb2-7"><a href="#cb2-7" tabindex="-1"></a><span class="fu">contrasts</span>(dat<span class="sc">$</span>Group)</span></code></pre></div>
<pre><code>##   [,1] [,2] [,3]
## 1   -1   -1   -1
## 2    1    0    0
## 3    0    1    0
## 4    0    0    1</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(Score<span class="sc">~</span>Group,<span class="at">data=</span>dat)</span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Score ~ Group, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.06311 -0.27955 -0.00111  0.28531  1.65733 
## 
## Coefficients:
##             Estimate Std. Error t value
## (Intercept)  0.15619    0.03936   3.969
## Group1      -0.24675    0.07193  -3.430
## Group2       0.09692    0.06670   1.453
## Group3       0.29647    0.06670   4.445
##             Pr(&gt;|t|)    
## (Intercept) 0.000107 ***
## Group1      0.000760 ***
## Group2      0.148092    
## Group3      0.000016 ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5109 on 166 degrees of freedom
## Multiple R-squared:  0.1473, Adjusted R-squared:  0.1319 
## F-statistic: 9.557 on 3 and 166 DF,  p-value: 0.000007399</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="do">## means</span></span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>(mm<span class="ot">&lt;-</span><span class="fu">tapply</span>(dat<span class="sc">$</span>Score, dat<span class="sc">$</span>Group, mean))</span></code></pre></div>
<pre><code>##            1            2            3 
##  0.009545455 -0.090555556  0.253111111 
##            4 
##  0.452666667</code></pre>
</div>
<div id="r-emmeans" class="section level2">
<h2>R emmeans</h2>
<p>To employ <code>emmeans</code> package, we first estimate the model
(which coding system we use does not matter), then we run the function
<code>emm&lt;-emmeans(model,specs)</code>, where <code>specs</code> is
the factor for which we want to compare the means, and then we apply
<code>contrast(emm,contrast_type)</code> to the emmeans object.
<code>contrast_type</code> is a string equal to the contrast function we
want to use. We add <code>adjust="none"</code> to obtain the same
p-values as in the previous analyses, but any adjustment supported by
<code>emmeans</code> can be applied here. If we omit the
<code>adjust</code> option, the default multiplicity adjustment method
is “fdr” , cf. <a
href="https://www.google.it/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=1&amp;ved=0ahUKEwjqpImqvYLYAhVQpKQKHTcMBtUQFggqMAA&amp;url=https%3A%2F%2Fcran.r-project.org%2Fweb%2Fpackages%2Femmeans%2Femmeans.pdf&amp;usg=AOvVaw1kHsWAafZ1Rhf3b-f7uruS">emmeans
package</a>.</p>
<p>The <code>deviation</code> contrast it is named <code>eff</code> in
emmeans.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(Score<span class="sc">~</span>Group,<span class="at">data=</span>dat)</span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a>emm<span class="ot">&lt;-</span><span class="fu">emmeans</span>(model,<span class="sc">~</span>Group)</span>
<span id="cb8-4"><a href="#cb8-4" tabindex="-1"></a><span class="fu">contrast</span>(emm,<span class="st">&quot;eff&quot;</span>,<span class="at">reverse=</span>T,<span class="at">adjust =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<pre><code>##  contrast      estimate     SE  df t.ratio
##  Group1 effect  -0.1466 0.0672 166  -2.183
##  Group2 effect  -0.2467 0.0719 166  -3.430
##  Group3 effect   0.0969 0.0667 166   1.453
##  Group4 effect   0.2965 0.0667 166   4.445
##  p.value
##   0.0305
##   0.0008
##   0.1481
##   &lt;.0001</code></pre>
<p>Please notice that <code>emmeans</code> computes all possible
comparisons: group 1 against the grand mean, group 2 against the grand
mean, etc.</p>
</div>
</div>
<div id="contrast-simple-dummy" class="section level1">
<h1>Contrast: Simple &amp; Dummy</h1>
<div id="meaning-1" class="section level2">
<h2>Meaning</h2>
<p><b>Definition: </b><i> Compares each group with the first
group.</i></p>
</div>
<div id="jamovi-anova-1" class="section level2">
<h2><span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
ANOVA</h2>
<p>We set the contrasts to <code>simple</code></p>
<p><img src="rosetta/contrasts/c2.anova1.png" class="img-responsive" alt=""></p>
<p>Results:</p>
<p><img src="rosetta/contrasts/r.c2.anova1.png" class="img-responsive" alt=""></p>
</div>
<div id="jamovi-gamlj-glm-1" class="section level2">
<h2><span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
<span class="modulename">GAMLj</span> GLM</h2>
<p>This is <span class="modulename">GAMLj</span> default (since version
1.5). The contrasts in <span class="modulename">GAMLj</span> is
identical to the ANOVA module.</p>
<p><img src="rosetta/contrasts/c2.anova1.png" class="img-responsive" alt=""></p>
<p><img src="rosetta/contrasts/r.c2.gamlj1.png" class="img-responsive" alt=""></p>
</div>
<div id="spss-1" class="section level2">
<h2>SPSS</h2>
<p>Please note that SPSS default sets the last group as reference group,
thus to obtain the same results as before, we should set
<code>/CONTRAST(Group)=Simple(1)</code>, mind the “1”“, which
corresponds to”first” in the GUI options.</p>
<p><img src="rosetta/contrasts/c2.spss1.png" class="img-responsive" alt=""></p>
<pre><code>UNIANOVA Score BY Group
  /CONTRAST(Group)=Simple(1)
  /METHOD=SSTYPE(3)
  /INTERCEPT=INCLUDE
  /PRINT=TEST(LMATRIX)
  /CRITERIA=ALPHA(.05)
  /DESIGN=Group.

</code></pre>
<p>Results:</p>
<p><img src="rosetta/contrasts/r.c2.spss1.png" class="img-responsive" alt=""></p>
</div>
<div id="r-1" class="section level2">
<h2>R</h2>
<p>In R, simple contrast can be obtained as follows:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="do">#### contrast=simple #######</span></span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>dat<span class="sc">$</span>Group<span class="ot">&lt;-</span><span class="fu">factor</span>(dat<span class="sc">$</span>Group)</span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a>k<span class="ot">&lt;-</span><span class="dv">4</span> <span class="co"># number of levels</span></span>
<span id="cb11-4"><a href="#cb11-4" tabindex="-1"></a><span class="fu">contrasts</span>(dat<span class="sc">$</span>Group)<span class="ot">&lt;-</span><span class="fu">contr.treatment</span>(k)<span class="sc">-</span>(<span class="dv">1</span><span class="sc">/</span>k)</span>
<span id="cb11-5"><a href="#cb11-5" tabindex="-1"></a><span class="fu">contrasts</span>(dat<span class="sc">$</span>Group)</span></code></pre></div>
<pre><code>##       2     3     4
## 1 -0.25 -0.25 -0.25
## 2  0.75 -0.25 -0.25
## 3 -0.25  0.75 -0.25
## 4 -0.25 -0.25  0.75</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(Score<span class="sc">~</span>Group,<span class="at">data=</span>dat)</span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Score ~ Group, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.06311 -0.27955 -0.00111  0.28531  1.65733 
## 
## Coefficients:
##             Estimate Std. Error t value
## (Intercept)  0.15619    0.03936   3.969
## Group2      -0.10010    0.11481  -0.872
## Group3       0.24357    0.10831   2.249
## Group4       0.44312    0.10831   4.091
##              Pr(&gt;|t|)    
## (Intercept)  0.000107 ***
## Group2       0.384538    
## Group3       0.025846 *  
## Group4      0.0000668 ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5109 on 166 degrees of freedom
## Multiple R-squared:  0.1473, Adjusted R-squared:  0.1319 
## F-statistic: 9.557 on 3 and 166 DF,  p-value: 0.000007399</code></pre>
<p>If one need the uncentered <em>dummy</em> coding, it can be obtained
in R using <code>contr.treatment(k)</code>.</p>
</div>
<div id="r-emmeans-1" class="section level2">
<h2>R emmeans</h2>
<p>The <code>simple</code> contrast can be achieved in emmeans with
<code>dunnett</code>.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(Score<span class="sc">~</span>Group,<span class="at">data=</span>dat)</span>
<span id="cb15-2"><a href="#cb15-2" tabindex="-1"></a>emm<span class="ot">&lt;-</span><span class="fu">emmeans</span>(model,<span class="sc">~</span>Group)</span>
<span id="cb15-3"><a href="#cb15-3" tabindex="-1"></a><span class="fu">contrast</span>(emm,<span class="st">&quot;dunnett&quot;</span>,<span class="at">adjust =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<pre><code>##  contrast        estimate    SE  df t.ratio
##  Group2 - Group1   -0.100 0.115 166  -0.872
##  Group3 - Group1    0.244 0.108 166   2.249
##  Group4 - Group1    0.443 0.108 166   4.091
##  p.value
##   0.3845
##   0.0258
##   0.0001</code></pre>
</div>
<div id="simple-vs-dummy" class="section level2">
<h2>Simple vs Dummy</h2>
<p><span class="modulename">GAMLj</span> distinguishes between
<em>simple</em> and <em>dummy</em> coding schemes. They give equivalent
results in means comparisons, simple effects, and contrast coefficients.
The only difference is that the <code>Dummy</code> is not centered, and
so when the codes are involved in interactions, the effects of the other
variables have different meaning. In the presence of interactions, when
<em>simple</em> is used, the other variables effects are computed
averaging across the sample; when <em>dummy</em> is used, the other
variables effects are computed for the reference group (the first group)
defined by the <em>dummy</em> coding.</p>
</div>
</div>
<div id="contrast-repeated" class="section level1">
<h1>Contrast: Repeated</h1>
<p><b>Definition: </b><i> Compares each group with the subsequent
group</i></p>
<div id="jamovi-anova-2" class="section level2">
<h2><span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
ANOVA</h2>
<p><img src="rosetta/contrasts/c5.anova1.png" class="img-responsive" alt=""></p>
<p>Results:</p>
<p><img src="rosetta/contrasts/r.c5.anova1.png" class="img-responsive" alt=""></p>
</div>
<div id="jamovi-gamlj-glm-2" class="section level2">
<h2><span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
<span class="modulename">GAMLj</span> GLM</h2>
<p><img src="rosetta/contrasts/r.c5.gamlj1.png" class="img-responsive" alt=""></p>
</div>
<div id="spss-2" class="section level2">
<h2>SPSS</h2>
<pre><code>UNIANOVA Score BY Group
  /CONTRAST(Group)=REPEATED
  /METHOD=SSTYPE(3)
  /INTERCEPT=INCLUDE
  /PRINT=TEST(LMATRIX)
  /CRITERIA=ALPHA(.05)
  /DESIGN=Group.

</code></pre>
<p><img src="rosetta/contrasts/r.c5.spss1.png" class="img-responsive" alt=""></p>
</div>
<div id="r-2" class="section level2">
<h2>R</h2>
<p>R does not have an out-of-the-box contrast equivalent to
<code>repeated</code> contrast. One can, howerver, uses the
<code>contr.sdif()</code> function in <code>MASS</code> package. As
compared with <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
and SPSS the comparisons are in the opposite direction, so we simply
multiply the code by -1 (t-tests and p-values do not depend on
this):</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a>repeated<span class="ot">&lt;-</span>(<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span><span class="fu">contr.sdif</span>(<span class="dv">4</span>) </span>
<span id="cb18-3"><a href="#cb18-3" tabindex="-1"></a>repeated</span></code></pre></div>
<pre><code>##     2-1  3-2   4-3
## 1  0.75  0.5  0.25
## 2 -0.25  0.5  0.25
## 3 -0.25 -0.5  0.25
## 4 -0.25 -0.5 -0.75</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="fu">contrasts</span>(dat<span class="sc">$</span>Group)<span class="ot">&lt;-</span>repeated</span>
<span id="cb20-2"><a href="#cb20-2" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Score<span class="sc">~</span>Group,<span class="at">data=</span>dat))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Score ~ Group, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.06311 -0.27955 -0.00111  0.28531  1.65733 
## 
## Coefficients:
##             Estimate Std. Error t value
## (Intercept)  0.15619    0.03936   3.969
## Group2-1     0.10010    0.11481   0.872
## Group3-2    -0.34367    0.11424  -3.008
## Group4-3    -0.19956    0.10770  -1.853
##             Pr(&gt;|t|)    
## (Intercept) 0.000107 ***
## Group2-1    0.384538    
## Group3-2    0.003036 ** 
## Group4-3    0.065681 .  
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5109 on 166 degrees of freedom
## Multiple R-squared:  0.1473, Adjusted R-squared:  0.1319 
## F-statistic: 9.557 on 3 and 166 DF,  p-value: 0.000007399</code></pre>
<p>… and we’re just fine.</p>
</div>
<div id="r-emmeans-2" class="section level2">
<h2>R emmeans</h2>
<p>The <code>repeated</code> contrast can be achieved in emmeans with
<code>consec</code>. To align the results to the <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
SPSS, we should reverse the contrast coding, with the option
<code>reverse</code>.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(Score<span class="sc">~</span>Group,<span class="at">data=</span>dat)</span>
<span id="cb22-2"><a href="#cb22-2" tabindex="-1"></a>emm<span class="ot">&lt;-</span><span class="fu">emmeans</span>(model,<span class="sc">~</span>Group)</span>
<span id="cb22-3"><a href="#cb22-3" tabindex="-1"></a><span class="fu">contrast</span>(emm,<span class="st">&quot;consec&quot;</span>,<span class="at">adjust =</span> <span class="st">&quot;none&quot;</span>,<span class="at">reverse=</span>T)</span></code></pre></div>
<pre><code>##  contrast        estimate    SE  df t.ratio
##  Group1 - Group2    0.100 0.115 166   0.872
##  Group2 - Group3   -0.344 0.114 166  -3.008
##  Group3 - Group4   -0.200 0.108 166  -1.853
##  p.value
##   0.3845
##   0.0030
##   0.0657</code></pre>
</div>
</div>
<div id="contrast-polynomial" class="section level1">
<h1>Contrast: Polynomial</h1>
<p><b>Definition: </b><i> Test polynomial (linear, quadratic, cubic,
etc.) trends in the means pattern</i></p>
<div id="jamovi-anova-3" class="section level2">
<h2><span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
ANOVA</h2>
<p><img src="rosetta/contrasts/c6.anova1.png" class="img-responsive" alt=""></p>
<p>Results:</p>
<p><img src="rosetta/contrasts/r.c6.anova1.png" class="img-responsive" alt=""></p>
</div>
<div id="jamovi-gamlj-glm-3" class="section level2">
<h2><span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
<span class="modulename">GAMLj</span> GLM</h2>
<p><img src="rosetta/contrasts/r.c6.gamlj1.png" class="img-responsive" alt=""></p>
</div>
<div id="spss-3" class="section level2">
<h2>SPSS</h2>
<pre><code>UNIANOVA Score BY Group
  /CONTRAST(Group)=POLYNOMIAL
  /METHOD=SSTYPE(3)
  /INTERCEPT=INCLUDE
  /PRINT=TEST(LMATRIX)
  /CRITERIA=ALPHA(.05)
  /DESIGN=Group.

</code></pre>
<p><img src="rosetta/contrasts/r.c6.spss1.png" class="img-responsive" alt=""></p>
</div>
<div id="r-3" class="section level2">
<h2>R</h2>
<p>R has an out-of-the-box contrast named <code>contr.poly()</code>
contrast. It works like a sharm.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a><span class="fu">contrasts</span>(dat<span class="sc">$</span>Group)<span class="ot">&lt;-</span><span class="fu">contr.poly</span>(<span class="dv">4</span>)</span>
<span id="cb25-2"><a href="#cb25-2" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Score<span class="sc">~</span>Group,<span class="at">data=</span>dat))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Score ~ Group, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.06311 -0.27955 -0.00111  0.28531  1.65733 
## 
## Coefficients:
##             Estimate Std. Error t value
## (Intercept)  0.15619    0.03936   3.969
## Group.L      0.37410    0.07702   4.857
## Group.Q      0.14983    0.07871   1.904
## Group.C     -0.13145    0.08037  -1.636
##               Pr(&gt;|t|)    
## (Intercept)   0.000107 ***
## Group.L     0.00000273 ***
## Group.Q       0.058702 .  
## Group.C       0.103809    
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5109 on 166 degrees of freedom
## Multiple R-squared:  0.1473, Adjusted R-squared:  0.1319 
## F-statistic: 9.557 on 3 and 166 DF,  p-value: 0.000007399</code></pre>
<p>… and we can sleep like babies.</p>
</div>
<div id="r-emmeans-3" class="section level2">
<h2>R emmeans</h2>
<p>The <code>poly</code> contrast has a direct implementation in
<code>emmeans</code> with <code>poly</code>.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(Score<span class="sc">~</span>Group,<span class="at">data=</span>dat)</span>
<span id="cb27-2"><a href="#cb27-2" tabindex="-1"></a>emm<span class="ot">&lt;-</span><span class="fu">emmeans</span>(model,<span class="sc">~</span>Group)</span>
<span id="cb27-3"><a href="#cb27-3" tabindex="-1"></a><span class="fu">contrast</span>(emm,<span class="st">&quot;poly&quot;</span>,<span class="at">adjust =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<pre><code>##  contrast  estimate    SE  df t.ratio p.value
##  linear       1.673 0.344 166   4.857  &lt;.0001
##  quadratic    0.300 0.157 166   1.904  0.0587
##  cubic       -0.588 0.359 166  -1.636  0.1038</code></pre>
</div>
</div>
<div id="contrast-difference" class="section level1">
<h1>Contrast: Difference</h1>
<p>Difference and helmert contrasts are great source of confusion when
one is comparing different software results. SPSS and <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
use the same definition for them, but R has a different implementation.
Different authors uses different definitions, so be aware of which
comparisons are implemented.</p>
<p><b>Definition: </b><i>Compares each group with the average of
previous groups.</i></p>
<p>This is sometimes named <em>Reverse Helmert Coding</em> , cf. <a
href="https://stats.idre.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/">UCLA
idre web site</a>.</p>
<div id="jamovi-anova-4" class="section level2">
<h2><span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
ANOVA</h2>
<p><img src="rosetta/contrasts/c3.anova1.png" class="img-responsive" alt=""></p>
<p>Results:</p>
<p><img src="rosetta/contrasts/r.c3.anova1.png" class="img-responsive" alt=""></p>
</div>
<div id="jamovi-gamlj-glm-4" class="section level2">
<h2><span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
<span class="modulename">GAMLj</span> GLM</h2>
<p><img src="rosetta/contrasts/r.c3.gamlj1.png" class="img-responsive" alt=""></p>
</div>
<div id="spss-4" class="section level2">
<h2>SPSS</h2>
<pre><code>UNIANOVA Score BY Group
  /CONTRAST(Group)=DIFFERENCE
  /METHOD=SSTYPE(3)
  /INTERCEPT=INCLUDE
  /PRINT=TEST(LMATRIX)
  /CRITERIA=ALPHA(.05)
  /DESIGN=Group.

</code></pre>
<p><img src="rosetta/contrasts/r.c3.spss1.png" class="img-responsive" alt=""></p>
</div>
<div id="r-4" class="section level2">
<h2>R</h2>
<p>The t-tests and p-values associated with the <em>difference
contrast</em> can be obtained in R using the
<code>contr.helmert()</code> function. Despite the name,
<code>contr.helmert()</code> implements what is usually named “Reversed
Helmert contrast”. Obviously, this is perfectly fine (cf. <a
href="http://www.amazon.com/gp/product/0761922806/ref=as_li_ss_tl?ie=UTF8&amp;camp=1789&amp;creative=390957&amp;creativeASIN=0761922806&amp;linkCode=as2&amp;tag=curiousanduseful">An
R and S-Plus Companion to Applied Regression</a>), but one should be
aware of this difference. The contrast weights in R are scaled
differently than in SPSS or <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>,
thus the contrast values (the coefficients) are not identical to the
ones obtained in <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
and SPSS, but they are proportional to them (that is why the t-tests are
the same).</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a>dat<span class="sc">$</span>Group<span class="ot">&lt;-</span><span class="fu">factor</span>(dat<span class="sc">$</span>Group)</span>
<span id="cb30-2"><a href="#cb30-2" tabindex="-1"></a><span class="fu">contrasts</span>(dat<span class="sc">$</span>Group)<span class="ot">&lt;-</span><span class="fu">contr.helmert</span>(<span class="dv">4</span>)</span>
<span id="cb30-3"><a href="#cb30-3" tabindex="-1"></a><span class="fu">contrasts</span>(dat<span class="sc">$</span>Group)</span></code></pre></div>
<pre><code>##   [,1] [,2] [,3]
## 1   -1   -1   -1
## 2    1   -1   -1
## 3    0    2   -1
## 4    0    0    3</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(Score<span class="sc">~</span>Group,<span class="at">data=</span>dat)</span>
<span id="cb32-2"><a href="#cb32-2" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Score ~ Group, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.06311 -0.27955 -0.00111  0.28531  1.65733 
## 
## Coefficients:
##             Estimate Std. Error t value
## (Intercept)  0.15619    0.03936   3.969
## Group1      -0.05005    0.05741  -0.872
## Group2       0.09787    0.03179   3.079
## Group3       0.09882    0.02223   4.445
##             Pr(&gt;|t|)    
## (Intercept) 0.000107 ***
## Group1      0.384538    
## Group2      0.002433 ** 
## Group3      0.000016 ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5109 on 166 degrees of freedom
## Multiple R-squared:  0.1473, Adjusted R-squared:  0.1319 
## F-statistic: 9.557 on 3 and 166 DF,  p-value: 0.000007399</code></pre>
<p>To obtain the <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>/SPSS
estimate values in R, we should multiply the coefficients obtained in R
by the index of the column of the contrasts (starting from 2 because 1
is for the intercept). To make things a bit more general, we can define
a <em>conversion vector</em> that works both for deviation and helmert
contrasts. Let the <em>conversion vector</em> be <span
class="math inline">\(\mathbf{cv}=max(c_i)+1\)</span>, where <span
class="math inline">\(c_i\)</span> is a column of the contrast
matrix.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a>cv<span class="ot">&lt;-</span><span class="fu">apply</span>(<span class="fu">contr.helmert</span>(<span class="dv">4</span>),<span class="dv">2</span>,max)<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb34-2"><a href="#cb34-2" tabindex="-1"></a>cv</span></code></pre></div>
<pre><code>## [1] 2 3 4</code></pre>
<p>To obtain the same coefficients in R and in <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>/SPSS,
we can multiply the model coefficients by <span
class="math inline">\(\mathbf{cv}\)</span></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" tabindex="-1"></a><span class="fu">coef</span>(model)[<span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>)]<span class="sc">*</span>cv</span></code></pre></div>
<pre><code>##     Group1     Group2     Group3 
## -0.1001010  0.2936162  0.3952997</code></pre>
<p>Or divide the contrast weights by <span
class="math inline">\(\mathbf{cv}\)</span></p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" tabindex="-1"></a><span class="do">### make a diagonal matrix with cv in the diagonal ##########</span></span>
<span id="cb38-2"><a href="#cb38-2" tabindex="-1"></a>diag_cv<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">rep</span>(cv,<span class="at">each=</span><span class="dv">4</span>),<span class="at">ncol=</span><span class="dv">3</span>)</span>
<span id="cb38-3"><a href="#cb38-3" tabindex="-1"></a><span class="fu">contrasts</span>(dat<span class="sc">$</span>Group)<span class="ot">&lt;-</span><span class="fu">contr.helmert</span>(<span class="dv">4</span>)<span class="sc">/</span>diag_cv</span>
<span id="cb38-4"><a href="#cb38-4" tabindex="-1"></a><span class="fu">contrasts</span>(dat<span class="sc">$</span>Group)</span></code></pre></div>
<pre><code>##   [,1]       [,2]  [,3]
## 1 -0.5 -0.3333333 -0.25
## 2  0.5 -0.3333333 -0.25
## 3  0.0  0.6666667 -0.25
## 4  0.0  0.0000000  0.75</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(Score<span class="sc">~</span>Group,<span class="at">data=</span>dat)</span>
<span id="cb40-2"><a href="#cb40-2" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Score ~ Group, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.06311 -0.27955 -0.00111  0.28531  1.65733 
## 
## Coefficients:
##             Estimate Std. Error t value
## (Intercept)  0.15619    0.03936   3.969
## Group1      -0.10010    0.11481  -0.872
## Group2       0.29362    0.09537   3.079
## Group3       0.39530    0.08893   4.445
##             Pr(&gt;|t|)    
## (Intercept) 0.000107 ***
## Group1      0.384538    
## Group2      0.002433 ** 
## Group3      0.000016 ***
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5109 on 166 degrees of freedom
## Multiple R-squared:  0.1473, Adjusted R-squared:  0.1319 
## F-statistic: 9.557 on 3 and 166 DF,  p-value: 0.000007399</code></pre>
<p>… and we get the same values, t-tests and p-values as in <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
and SPSS.</p>
</div>
<div id="r-emmeans-4" class="section level2">
<h2>R emmeans</h2>
<p>Difference and helmert are not implemented in emmeans package, but
<code>emmeans</code> has a very clever way to implement custom contrast
coding. We need to define a function whose name ends with
<code>.emmc</code> and returns the coding as a data.frame, and then pass
it to <code>emmeans</code> <code>contrasts</code> function. The coding
weights are the one of the contrast matrix used in SPSS (see <a
href="#contrast_matrix_and_model_matrix_details">contrast matrix vs
model matrix</a> for details).</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" tabindex="-1"></a><span class="fu">library</span>(MASS) <span class="do">## needed for ginv(), see below </span></span>
<span id="cb42-2"><a href="#cb42-2" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" tabindex="-1"></a>difference.emmc<span class="ot">&lt;&lt;-</span><span class="cf">function</span>(levs,wts) {</span>
<span id="cb42-4"><a href="#cb42-4" tabindex="-1"></a>  n<span class="ot">&lt;-</span><span class="fu">length</span>(levs)</span>
<span id="cb42-5"><a href="#cb42-5" tabindex="-1"></a>  <span class="do">#### model matrix ########</span></span>
<span id="cb42-6"><a href="#cb42-6" tabindex="-1"></a>  con_weights<span class="ot">&lt;-</span><span class="fu">contr.helmert</span>(n)</span>
<span id="cb42-7"><a href="#cb42-7" tabindex="-1"></a>  cv<span class="ot">&lt;-</span><span class="fu">apply</span>(con_weights,<span class="dv">2</span>,max)<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb42-8"><a href="#cb42-8" tabindex="-1"></a>  diag_cv<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">rep</span>(cv,<span class="at">each=</span>n),<span class="at">ncol=</span>n<span class="dv">-1</span>)</span>
<span id="cb42-9"><a href="#cb42-9" tabindex="-1"></a>  model_mat<span class="ot">&lt;-</span>con_weights<span class="sc">/</span>diag_cv</span>
<span id="cb42-10"><a href="#cb42-10" tabindex="-1"></a></span>
<span id="cb42-11"><a href="#cb42-11" tabindex="-1"></a>  <span class="do">##### contrast matrix ########</span></span>
<span id="cb42-12"><a href="#cb42-12" tabindex="-1"></a>  cont_mat<span class="ot">&lt;-</span><span class="fu">ginv</span>(<span class="fu">t</span>(model_mat))</span>
<span id="cb42-13"><a href="#cb42-13" tabindex="-1"></a>  M <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(cont_mat)</span>
<span id="cb42-14"><a href="#cb42-14" tabindex="-1"></a>  <span class="fu">names</span>(M) <span class="ot">&lt;-</span> <span class="fu">paste</span>(levs[<span class="sc">-</span><span class="dv">1</span>],<span class="st">&quot;vs previous&quot;</span>)</span>
<span id="cb42-15"><a href="#cb42-15" tabindex="-1"></a>  <span class="fu">attr</span>(M, <span class="st">&quot;desc&quot;</span>) <span class="ot">&lt;-</span> <span class="st">&quot;Difference contrasts&quot;</span></span>
<span id="cb42-16"><a href="#cb42-16" tabindex="-1"></a>  M</span>
<span id="cb42-17"><a href="#cb42-17" tabindex="-1"></a>}</span>
<span id="cb42-18"><a href="#cb42-18" tabindex="-1"></a><span class="do">#### contrast matrix #########</span></span>
<span id="cb42-19"><a href="#cb42-19" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">difference.emmc</span>(<span class="fu">levels</span>(dat<span class="sc">$</span>Group)),<span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##   2 vs previous 3 vs previous 4 vs previous
## 1            -1          -0.5        -0.333
## 2             1          -0.5        -0.333
## 3             0           1.0        -0.333
## 4             0           0.0         1.000</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" tabindex="-1"></a><span class="do">#### results ##############</span></span>
<span id="cb44-2"><a href="#cb44-2" tabindex="-1"></a><span class="fu">contrast</span>(emm,<span class="at">method=</span><span class="st">&quot;difference&quot;</span>,<span class="at">adjust=</span><span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<pre><code>##  contrast           estimate     SE  df
##  Group2 vs previous   -0.100 0.1150 166
##  Group3 vs previous    0.294 0.0954 166
##  Group4 vs previous    0.395 0.0889 166
##  t.ratio p.value
##   -0.872  0.3845
##    3.079  0.0024
##    4.445  &lt;.0001</code></pre>
<p>Same results as before.</p>
</div>
</div>
<div id="contrast-helmert" class="section level1">
<h1>Contrast: Helmert</h1>
<p><b>Definition: </b><i>Compares each group with the average of
subsequent groups</i></p>
<div id="jamovi-anova-5" class="section level2">
<h2><span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
ANOVA</h2>
<p><img src="rosetta/contrasts/c4.anova1.png" class="img-responsive" alt=""></p>
<p>Results:</p>
<p><img src="rosetta/contrasts/r.c4.anova1.png" class="img-responsive" alt=""></p>
</div>
<div id="jamovi-gamlj-glm-5" class="section level2">
<h2><span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
<span class="modulename">GAMLj</span> GLM</h2>
<p><img src="rosetta/contrasts/r.c4.gamlj1.png" class="img-responsive" alt=""></p>
</div>
<div id="spss-5" class="section level2">
<h2>SPSS</h2>
<pre><code>UNIANOVA Score BY Group
  /CONTRAST(Group)=HELMERT
  /METHOD=SSTYPE(3)
  /INTERCEPT=INCLUDE
  /PRINT=TEST(LMATRIX)
  /CRITERIA=ALPHA(.05)
  /DESIGN=Group.
</code></pre>
<p><img src="rosetta/contrasts/r.c4.spss1.png" class="img-responsive" alt=""></p>
</div>
<div id="r-5" class="section level2">
<h2>R</h2>
<p>R defines helmert contrast in the reverse order as compared with
<span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>
and SPSS, and uses a different scaling. To obtain the helmert contrast
as it is was defined above, we should reverse
<code>contr.helmert()</code> and rescale the coding as we did for the
<code>difference</code> contrasts. Without rescaling, the t-test and
p-values are the same as in <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>/spss,
but the estimated values are different (but proportional).</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" tabindex="-1"></a>dat<span class="sc">$</span>Group<span class="ot">&lt;-</span><span class="fu">factor</span>(dat<span class="sc">$</span>Group)</span>
<span id="cb47-2"><a href="#cb47-2" tabindex="-1"></a><span class="fu">contrasts</span>(dat<span class="sc">$</span>Group)<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">rev</span>(<span class="fu">contr.helmert</span>(<span class="dv">4</span>)),<span class="at">ncol=</span><span class="dv">3</span>)</span>
<span id="cb47-3"><a href="#cb47-3" tabindex="-1"></a>con_weights<span class="ot">&lt;-</span><span class="fu">contrasts</span>(dat<span class="sc">$</span>Group)</span>
<span id="cb47-4"><a href="#cb47-4" tabindex="-1"></a><span class="do">#### not scaled contrast weights ######</span></span>
<span id="cb47-5"><a href="#cb47-5" tabindex="-1"></a>con_weights</span></code></pre></div>
<pre><code>##   [,1] [,2] [,3]
## 1    3    0    0
## 2   -1    2    0
## 3   -1   -1    1
## 4   -1   -1   -1</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(Score<span class="sc">~</span>Group,<span class="at">data=</span>dat)</span>
<span id="cb49-2"><a href="#cb49-2" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Score ~ Group, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.06311 -0.27955 -0.00111  0.28531  1.65733 
## 
## Coefficients:
##             Estimate Std. Error t value
## (Intercept)  0.15619    0.03936   3.969
## Group1      -0.04888    0.02240  -2.183
## Group2      -0.14781    0.03358  -4.402
## Group3      -0.09978    0.05385  -1.853
##              Pr(&gt;|t|)    
## (Intercept)  0.000107 ***
## Group1       0.030477 *  
## Group2      0.0000192 ***
## Group3       0.065681 .  
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5109 on 166 degrees of freedom
## Multiple R-squared:  0.1473, Adjusted R-squared:  0.1319 
## F-statistic: 9.557 on 3 and 166 DF,  p-value: 0.000007399</code></pre>
<p>To obtain the <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>/SPSS
values in R, we should compute <span
class="math inline">\(\mathbf{cv}=max(c_i)+1\)</span>, and multiply it
by the model coefficients.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" tabindex="-1"></a>cv<span class="ot">&lt;-</span><span class="fu">apply</span>(con_weights,<span class="dv">2</span>,max)<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb51-2"><a href="#cb51-2" tabindex="-1"></a>cv</span></code></pre></div>
<pre><code>## [1] 4 3 2</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" tabindex="-1"></a><span class="fu">coef</span>(model)[<span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>)]<span class="sc">*</span>cv</span></code></pre></div>
<pre><code>##     Group1     Group2     Group3 
## -0.1955286 -0.4434444 -0.1995556</code></pre>
<p>or divide the contrast weights by <span
class="math inline">\(\mathbf{cv}\)</span></p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" tabindex="-1"></a><span class="do">### make a diagonal matrix with cv in the diagonal ##########</span></span>
<span id="cb55-2"><a href="#cb55-2" tabindex="-1"></a>diag_cv<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">rep</span>(cv,<span class="at">each=</span><span class="dv">4</span>),<span class="at">ncol=</span><span class="dv">3</span>)</span>
<span id="cb55-3"><a href="#cb55-3" tabindex="-1"></a><span class="do">########  divide the contrast weights ##########</span></span>
<span id="cb55-4"><a href="#cb55-4" tabindex="-1"></a>helm<span class="ot">&lt;-</span>con_weights<span class="sc">/</span>diag_cv</span>
<span id="cb55-5"><a href="#cb55-5" tabindex="-1"></a></span>
<span id="cb55-6"><a href="#cb55-6" tabindex="-1"></a><span class="do">### scaled contrast weights ############</span></span>
<span id="cb55-7"><a href="#cb55-7" tabindex="-1"></a>helm</span></code></pre></div>
<pre><code>##    [,1]       [,2] [,3]
## 1  0.75  0.0000000  0.0
## 2 -0.25  0.6666667  0.0
## 3 -0.25 -0.3333333  0.5
## 4 -0.25 -0.3333333 -0.5</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" tabindex="-1"></a><span class="fu">contrasts</span>(dat<span class="sc">$</span>Group)<span class="ot">&lt;-</span>helm</span>
<span id="cb57-2"><a href="#cb57-2" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(Score<span class="sc">~</span>Group,<span class="at">data=</span>dat)</span>
<span id="cb57-3"><a href="#cb57-3" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Score ~ Group, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.06311 -0.27955 -0.00111  0.28531  1.65733 
## 
## Coefficients:
##             Estimate Std. Error t value
## (Intercept)  0.15619    0.03936   3.969
## Group1      -0.19553    0.08959  -2.183
## Group2      -0.44344    0.10075  -4.402
## Group3      -0.19956    0.10770  -1.853
##              Pr(&gt;|t|)    
## (Intercept)  0.000107 ***
## Group1       0.030477 *  
## Group2      0.0000192 ***
## Group3       0.065681 .  
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5109 on 166 degrees of freedom
## Multiple R-squared:  0.1473, Adjusted R-squared:  0.1319 
## F-statistic: 9.557 on 3 and 166 DF,  p-value: 0.000007399</code></pre>
<p>… and we’re happy campers.</p>
</div>
<div id="r-emmeans-5" class="section level2">
<h2>R emmeans</h2>
<p>We need to define a funtion whose name ends with <code>.emmc</code>
which returns the contrast matrix, and then pass it to emmeans
<code>contrasts</code>. The contrast matrix is the same used in SPSS and
can be obtained from the model matrix used in standard R (see <a
href="#contrast_matrix_vs_model_matrix">contrast matrix vs model
matrix</a> for details).</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" tabindex="-1"></a><span class="fu">library</span>(MASS) <span class="co"># needed for ginv(), see below</span></span>
<span id="cb59-2"><a href="#cb59-2" tabindex="-1"></a>helmert.emmc<span class="ot">&lt;&lt;-</span><span class="cf">function</span>(levs, wts) {</span>
<span id="cb59-3"><a href="#cb59-3" tabindex="-1"></a>  n<span class="ot">&lt;-</span><span class="fu">length</span>(levs)</span>
<span id="cb59-4"><a href="#cb59-4" tabindex="-1"></a>  <span class="do">#### build model matricx ######</span></span>
<span id="cb59-5"><a href="#cb59-5" tabindex="-1"></a>  con_weights<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">rev</span>(<span class="fu">contr.helmert</span>(n)),<span class="at">ncol=</span>n<span class="dv">-1</span>)</span>
<span id="cb59-6"><a href="#cb59-6" tabindex="-1"></a>  cv<span class="ot">&lt;-</span><span class="fu">apply</span>(con_weights,<span class="dv">2</span>,max)<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb59-7"><a href="#cb59-7" tabindex="-1"></a>  diag_cv<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">rep</span>(cv,<span class="at">each=</span>n),<span class="at">ncol=</span>n<span class="dv">-1</span>)</span>
<span id="cb59-8"><a href="#cb59-8" tabindex="-1"></a>  model_mat<span class="ot">&lt;-</span>con_weights<span class="sc">/</span>diag_cv</span>
<span id="cb59-9"><a href="#cb59-9" tabindex="-1"></a>  <span class="do">#### obtain contrast matrix #######</span></span>
<span id="cb59-10"><a href="#cb59-10" tabindex="-1"></a>  cont_mat<span class="ot">&lt;-</span><span class="fu">ginv</span>(<span class="fu">t</span>(model_mat))</span>
<span id="cb59-11"><a href="#cb59-11" tabindex="-1"></a>  </span>
<span id="cb59-12"><a href="#cb59-12" tabindex="-1"></a>  M <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(cont_mat)</span>
<span id="cb59-13"><a href="#cb59-13" tabindex="-1"></a>  <span class="fu">names</span>(M) <span class="ot">&lt;-</span> <span class="fu">paste</span>(levs[<span class="dv">1</span><span class="sc">:</span>(<span class="fu">length</span>(levs)<span class="sc">-</span><span class="dv">1</span>)],<span class="st">&quot;vs subsequent&quot;</span>)</span>
<span id="cb59-14"><a href="#cb59-14" tabindex="-1"></a>  <span class="fu">attr</span>(M, <span class="st">&quot;desc&quot;</span>) <span class="ot">&lt;-</span> <span class="st">&quot;Helmert contrasts&quot;</span></span>
<span id="cb59-15"><a href="#cb59-15" tabindex="-1"></a>  M</span>
<span id="cb59-16"><a href="#cb59-16" tabindex="-1"></a>}</span>
<span id="cb59-17"><a href="#cb59-17" tabindex="-1"></a></span>
<span id="cb59-18"><a href="#cb59-18" tabindex="-1"></a><span class="fu">helmert.emmc</span>(<span class="fu">levels</span>(dat<span class="sc">$</span>Group))</span></code></pre></div>
<pre><code>##   1 vs subsequent            2 vs subsequent
## 1       1.0000000 -0.00000000000000006343273
## 2      -0.3333333  1.00000000000000000000000
## 3      -0.3333333 -0.50000000000000011102230
## 4      -0.3333333 -0.50000000000000011102230
##             3 vs subsequent
## 1 -0.0000000000000001098687
## 2 -0.0000000000000001256066
## 3  0.9999999999999995559108
## 4 -0.9999999999999997779554</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" tabindex="-1"></a><span class="fu">contrast</span>(emm,<span class="st">&quot;helmert&quot;</span>,<span class="at">adjust=</span><span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<pre><code>##  contrast             estimate     SE  df
##  Group1 vs subsequent   -0.196 0.0896 166
##  Group2 vs subsequent   -0.443 0.1010 166
##  Group3 vs subsequent   -0.200 0.1080 166
##  t.ratio p.value
##   -2.183  0.0305
##   -4.402  &lt;.0001
##   -1.853  0.0657</code></pre>
<p>Same results!</p>
</div>
</div>
<div id="contrast-matrix-vs-model-matrix" class="section level1">
<h1>Contrast matrix vs model matrix</h1>
<p>We have seen that <span
class="jamovi"><a href="http://www.jamovi.org" target="_blank">jamovi</a></span>,
SPSS and <code>emmeans</code> provide descriptions of the comparisons
being estimated as labels of the contrast. However, if one needs to
deepen the understanding of the contrast at hand, one needs to examine
the contrast coding scheme. SPSS and <code>emmeans</code> can show the
coding scheme in the form of <strong>contrast matrix</strong>.</p>
<p>To visualize the contrast matrix in in SPSS one uses the option
<code>/PRINT=TEST(LMATRIX)</code> , and in <code>emmeans</code> one can
use the function <code>coef()</code> on the contrast object output by
the <code>contrast()</code> function.</p>
<p>Let’s see an example using the <code>repeated</code> contrast:</p>
<p>This is the <code>LMATRIX</code> one gets in SPSS</p>
<p><img src="rosetta/contrasts/r.c7.spss1.png" class="img-responsive" alt=""></p>
<p>and this is the contrast matrix one gets from
<code>emmeans</code>:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb63-2"><a href="#cb63-2" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(Score<span class="sc">~</span>Group,<span class="at">data=</span>dat)</span>
<span id="cb63-3"><a href="#cb63-3" tabindex="-1"></a>emm<span class="ot">&lt;-</span><span class="fu">emmeans</span>(model,<span class="sc">~</span>Group)</span>
<span id="cb63-4"><a href="#cb63-4" tabindex="-1"></a>cont<span class="ot">&lt;-</span><span class="fu">contrast</span>(emm,<span class="st">&quot;consec&quot;</span>,<span class="at">reverse=</span>T,<span class="at">adjust =</span> <span class="st">&quot;none&quot;</span>)</span>
<span id="cb63-5"><a href="#cb63-5" tabindex="-1"></a><span class="fu">coef</span>(cont)</span></code></pre></div>
<pre><code>##        Group c.1 c.2 c.3
## Group1     1   1   0   0
## Group2     2  -1   1   0
## Group3     3   0  -1   1
## Group4     4   0   0  -1</code></pre>
<p>When it comes to R model estimation ( <code>lm()</code>,
<code>lmer()</code>, <code>glm()</code> ), however, we should notice
that to obtain the same comparisons obtained by the other packages, one
needs to code the comparisons in form of the <strong>model
matrix</strong>, not the contrast matrix. This may be confusing, but
that’s the way it is.</p>
<p>In fact, upon inspecting the coding scheme generated by the
<code>contr.*</code> functions, one see that the coding does not
correspond to the <em>contrast matrix</em> seen before.</p>
<p>For <code>repeated</code> contrasts in R we use:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" tabindex="-1"></a>(<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span><span class="fu">contr.sdif</span>(<span class="dv">4</span>)</span></code></pre></div>
<pre><code>##     2-1  3-2   4-3
## 1  0.75  0.5  0.25
## 2 -0.25  0.5  0.25
## 3 -0.25 -0.5  0.25
## 4 -0.25 -0.5 -0.75</code></pre>
<p>Recall (cf. the repeated contrast results above) that the results are
identical between the R, SPSS and <code>emmeans</code>, even thought the
coding seems different.</p>
<p>Now, if you try to use the SPSS LMATRIX in R, you are not going to
get the results expected by the <code>repeated</code> contrast. Indeed
(coefficients were <code>.100,-.344,-.200</code>) :</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" tabindex="-1"></a>ones<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>),<span class="at">ncol=</span><span class="dv">3</span>)</span>
<span id="cb67-2"><a href="#cb67-2" tabindex="-1"></a>ones</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    0    0
## [2,]   -1    1    0
## [3,]    0   -1    1
## [4,]    0    0   -1</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" tabindex="-1"></a><span class="fu">contrasts</span>(dat<span class="sc">$</span>Group)<span class="ot">&lt;-</span>ones</span>
<span id="cb69-2"><a href="#cb69-2" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Score ~ Group, data = dat)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.06311 -0.27955 -0.00111  0.28531  1.65733 
## 
## Coefficients:
##             Estimate Std. Error t value
## (Intercept)  0.15619    0.03936   3.969
## Group1      -0.19553    0.08959  -2.183
## Group2      -0.44344    0.10075  -4.402
## Group3      -0.19956    0.10770  -1.853
##              Pr(&gt;|t|)    
## (Intercept)  0.000107 ***
## Group1       0.030477 *  
## Group2      0.0000192 ***
## Group3       0.065681 .  
## ---
## Signif. codes:  
## 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.5109 on 166 degrees of freedom
## Multiple R-squared:  0.1473, Adjusted R-squared:  0.1319 
## F-statistic: 9.557 on 3 and 166 DF,  p-value: 0.000007399</code></pre>
<p>The reason of this discrepancy is that the LMATRIX is the contrast
matrix, a matrix that shows the linear hypotheses implied by the
contrast and represents the starting point of the coding system, not the
model matrix itself. Thus, the constrast matrix (SPSS LMATRIX) is useful
to understand what is going on in the comparisons: by inspecting the
contrast matrix one can easily see that in column 1 groups 1 and 2 are
compared, in column 2 groups 2 vs 3, and so on.</p>
<p>A clear technical explanation is provided in <a
href="https://cran.r-project.org/web/packages/codingMatrices/vignettes/codingMatrices.pdf">Venables
2017</a>, where you find the definition of the contrast matrix
(<strong><span class="math inline">\(C\)</span></strong> in the
Venable’s vignette) and the model matrix (<strong><span
class="math inline">\(B\)</span></strong> in the vignette).</p>
<p>Ok, but what is the relation between the contrast matrix and the R
model matrix? or even better: How do I get from the contrast matrix to
the R model matrix? Just <strong>take the inverse of the contrast matrix
and traspose it</strong>. In R, one can take the inverse of a matrix by
using <code>MASS::ginv()</code> function. Let’s see:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" tabindex="-1"></a><span class="do">##### SPSS LMATRIX ####</span></span>
<span id="cb71-2"><a href="#cb71-2" tabindex="-1"></a>ones</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    0    0
## [2,]   -1    1    0
## [3,]    0   -1    1
## [4,]    0    0   -1</code></pre>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" tabindex="-1"></a><span class="do">### take the inverse ####</span></span>
<span id="cb73-2"><a href="#cb73-2" tabindex="-1"></a>iones<span class="ot">&lt;-</span><span class="fu">ginv</span>(ones)</span>
<span id="cb73-3"><a href="#cb73-3" tabindex="-1"></a><span class="do">### transpose it </span><span class="al">###</span></span>
<span id="cb73-4"><a href="#cb73-4" tabindex="-1"></a><span class="fu">t</span>(iones)</span></code></pre></div>
<pre><code>##       [,1] [,2]  [,3]
## [1,]  0.75  0.5  0.25
## [2,] -0.25  0.5  0.25
## [3,] -0.25 -0.5  0.25
## [4,] -0.25 -0.5 -0.75</code></pre>
<p>and there you are: the R model matrix.</p>
<p>Does it work in general? Yes! Take <code>deviation</code> contrast,
with group 1 omitted.</p>
<p>SPSS LMATRIX is:
<img src="rosetta/contrasts/r.c7.spss2.png" class="img-responsive" alt=""></p>
<p>and R model matrix we have seen before:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" tabindex="-1"></a>(deviation<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">rev</span>(<span class="fu">contr.sum</span>(<span class="dv">4</span>)),<span class="at">ncol=</span><span class="dv">3</span>))</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]   -1   -1   -1
## [2,]    1    0    0
## [3,]    0    1    0
## [4,]    0    0    1</code></pre>
<p>They seem different, but taking the inverse of the LMATRIX and
transposing it, we get the R coding system.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" tabindex="-1"></a><span class="do">##### SPSS LMATRIX ####</span></span>
<span id="cb77-2"><a href="#cb77-2" tabindex="-1"></a>lmat<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">rep</span>(<span class="sc">-</span>.<span class="dv">25</span>,<span class="dv">12</span>),<span class="at">ncol=</span><span class="dv">3</span>)</span>
<span id="cb77-3"><a href="#cb77-3" tabindex="-1"></a>lmat[<span class="dv">2</span>,<span class="dv">1</span>]<span class="ot">&lt;-</span>.<span class="dv">75</span></span>
<span id="cb77-4"><a href="#cb77-4" tabindex="-1"></a>lmat[<span class="dv">3</span>,<span class="dv">2</span>]<span class="ot">&lt;-</span>.<span class="dv">75</span></span>
<span id="cb77-5"><a href="#cb77-5" tabindex="-1"></a>lmat[<span class="dv">4</span>,<span class="dv">3</span>]<span class="ot">&lt;-</span>.<span class="dv">75</span></span>
<span id="cb77-6"><a href="#cb77-6" tabindex="-1"></a>lmat</span></code></pre></div>
<pre><code>##       [,1]  [,2]  [,3]
## [1,] -0.25 -0.25 -0.25
## [2,]  0.75 -0.25 -0.25
## [3,] -0.25  0.75 -0.25
## [4,] -0.25 -0.25  0.75</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" tabindex="-1"></a><span class="do">### take the inverse ####</span></span>
<span id="cb79-2"><a href="#cb79-2" tabindex="-1"></a>ilmat<span class="ot">&lt;-</span><span class="fu">ginv</span>(lmat)</span>
<span id="cb79-3"><a href="#cb79-3" tabindex="-1"></a><span class="do">### transpose it </span><span class="al">###</span></span>
<span id="cb79-4"><a href="#cb79-4" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">t</span>(ilmat),<span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]   -1   -1   -1
## [2,]    1    0    0
## [3,]    0    1    0
## [4,]    0    0    1</code></pre>
<p>There you have the actual model matrix.</p>
<p>Let us be sure and check polynomial contrasts.</p>
<p>SPSS LMATRIX is:
<img src="rosetta/contrasts/r.c7.spss3.png" class="img-responsive" alt=""></p>
<p>R model matrix:</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" tabindex="-1"></a>(polynom<span class="ot">&lt;-</span><span class="fu">contr.poly</span>(<span class="dv">4</span>))</span></code></pre></div>
<pre><code>##              .L   .Q         .C
## [1,] -0.6708204  0.5 -0.2236068
## [2,] -0.2236068 -0.5  0.6708204
## [3,]  0.2236068 -0.5 -0.6708204
## [4,]  0.6708204  0.5  0.2236068</code></pre>
<p>They are the same this time! Does it means that in this case the
“inversion” does not apply? Well, it does apply, but because the
polynomial contrast codes are orthogonal, the inverse of the contrast
matrix is equal to the transpose of the contrast matrix, thus taking the
inverse and then transpose it gives back the same matrix (cf <a
href="https://en.wikipedia.org/wiki/Orthogonal_matrix">orthogonal
matrix</a>)</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" tabindex="-1"></a>ipoly<span class="ot">&lt;-</span><span class="fu">ginv</span>(polynom)</span>
<span id="cb83-2"><a href="#cb83-2" tabindex="-1"></a><span class="fu">t</span>(ipoly)</span></code></pre></div>
<pre><code>##            [,1] [,2]       [,3]
## [1,] -0.6708204  0.5 -0.2236068
## [2,] -0.2236068 -0.5  0.6708204
## [3,]  0.2236068 -0.5 -0.6708204
## [4,]  0.6708204  0.5  0.2236068</code></pre>
<div id="building-custom-contrast-in-emmeans" class="section level2">
<h2>Building custom contrast in emmeans</h2>
<p>We have seen that <code>emmeans</code> allows to define custom
contrast coding. When we do that, we should remember that we need to
define the contrast matrix, <strong>not</strong> the model matrix. Thus,
for repeated contrast, in R we used <code>(-1)*contr.sdif(n)</code>:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" tabindex="-1"></a>(rcodes<span class="ot">&lt;-</span>(<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span><span class="fu">contr.sdif</span>(<span class="dv">4</span>))</span></code></pre></div>
<pre><code>##     2-1  3-2   4-3
## 1  0.75  0.5  0.25
## 2 -0.25  0.5  0.25
## 3 -0.25 -0.5  0.25
## 4 -0.25 -0.5 -0.75</code></pre>
<p>and <code>emmeans</code> uses:</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" tabindex="-1"></a>cont<span class="ot">&lt;-</span><span class="fu">contrast</span>(emm,<span class="st">&quot;consec&quot;</span>,<span class="at">referse=</span>T,<span class="at">adjust =</span> <span class="st">&quot;none&quot;</span>)</span>
<span id="cb87-2"><a href="#cb87-2" tabindex="-1"></a>(weigths<span class="ot">&lt;-</span><span class="fu">coef</span>(cont)[,<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>])</span></code></pre></div>
<pre><code>##        c.1 c.2 c.3
## Group1  -1   0   0
## Group2   1  -1   0
## Group3   0   1  -1
## Group4   0   0   1</code></pre>
<p>To get the contrast matrix from the model matrix we neet to get the
<strong>inverse of the transpose</strong>:</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" tabindex="-1"></a><span class="do">#### model matrix ######</span></span>
<span id="cb89-2"><a href="#cb89-2" tabindex="-1"></a>rcodes</span></code></pre></div>
<pre><code>##     2-1  3-2   4-3
## 1  0.75  0.5  0.25
## 2 -0.25  0.5  0.25
## 3 -0.25 -0.5  0.25
## 4 -0.25 -0.5 -0.75</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" tabindex="-1"></a><span class="do">#### transpose the R model matrix ######</span></span>
<span id="cb91-2"><a href="#cb91-2" tabindex="-1"></a>tcodes<span class="ot">&lt;-</span><span class="fu">t</span>(rcodes)</span>
<span id="cb91-3"><a href="#cb91-3" tabindex="-1"></a><span class="do">#### invert it #####</span></span>
<span id="cb91-4"><a href="#cb91-4" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">ginv</span>(tcodes),<span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    0    0
## [2,]   -1    1    0
## [3,]    0   -1    1
## [4,]    0    0   -1</code></pre>
<p>Now we can build a custom contrast function for <code>emmeans</code>:
let’s do <code>helmert</code> as we defined above.</p>
<p>Let’s start with the model matrix used in R.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" tabindex="-1"></a>con_weights<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">rev</span>(<span class="fu">contr.helmert</span>(<span class="dv">4</span>)),<span class="at">ncol=</span><span class="dv">3</span>)</span>
<span id="cb93-2"><a href="#cb93-2" tabindex="-1"></a>cv<span class="ot">&lt;-</span><span class="fu">apply</span>(con_weights,<span class="dv">2</span>,max)<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb93-3"><a href="#cb93-3" tabindex="-1"></a>diag_cv<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">rep</span>(cv,<span class="at">each=</span><span class="dv">4</span>),<span class="at">ncol=</span><span class="dv">3</span>)</span>
<span id="cb93-4"><a href="#cb93-4" tabindex="-1"></a>helm<span class="ot">&lt;-</span>con_weights<span class="sc">/</span>diag_cv</span>
<span id="cb93-5"><a href="#cb93-5" tabindex="-1"></a>helm</span></code></pre></div>
<pre><code>##       [,1]       [,2] [,3]
## [1,]  0.75  0.0000000  0.0
## [2,] -0.25  0.6666667  0.0
## [3,] -0.25 -0.3333333  0.5
## [4,] -0.25 -0.3333333 -0.5</code></pre>
<p>Take the inverse of the transpose of it</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" tabindex="-1"></a>(contr_mat<span class="ot">&lt;-</span><span class="fu">ginv</span>(<span class="fu">t</span>(helm)))</span></code></pre></div>
<pre><code>##            [,1]                       [,2]
## [1,]  1.0000000 -0.00000000000000006343273
## [2,] -0.3333333  1.00000000000000000000000
## [3,] -0.3333333 -0.50000000000000011102230
## [4,] -0.3333333 -0.50000000000000011102230
##                           [,3]
## [1,] -0.0000000000000001098687
## [2,] -0.0000000000000001256066
## [3,]  0.9999999999999995559108
## [4,] -0.9999999999999997779554</code></pre>
<p>This is the contrast matrix we can pass to <code>emmeans</code>. We
just need to wrap it up in a function with <code>.emmc()</code>
reference class and <code>levels</code> as input.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" tabindex="-1"></a>helmert.emmc<span class="ot">&lt;&lt;-</span><span class="cf">function</span>(levs,wts) {</span>
<span id="cb97-2"><a href="#cb97-2" tabindex="-1"></a>  n<span class="ot">&lt;-</span><span class="fu">length</span>(levs)</span>
<span id="cb97-3"><a href="#cb97-3" tabindex="-1"></a>  con_weights<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">rev</span>(<span class="fu">contr.helmert</span>(n)),<span class="at">ncol=</span>n<span class="dv">-1</span>)</span>
<span id="cb97-4"><a href="#cb97-4" tabindex="-1"></a>  cv<span class="ot">&lt;-</span><span class="fu">apply</span>(con_weights,<span class="dv">2</span>,max)<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb97-5"><a href="#cb97-5" tabindex="-1"></a>  diag_cv<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">rep</span>(cv,<span class="at">each=</span>n),<span class="at">ncol=</span>n<span class="dv">-1</span>)</span>
<span id="cb97-6"><a href="#cb97-6" tabindex="-1"></a>  helm<span class="ot">&lt;-</span>con_weights<span class="sc">/</span>diag_cv</span>
<span id="cb97-7"><a href="#cb97-7" tabindex="-1"></a>  model_mat<span class="ot">&lt;-</span><span class="fu">ginv</span>(<span class="fu">t</span>(helm))</span>
<span id="cb97-8"><a href="#cb97-8" tabindex="-1"></a>  M <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(model_mat)</span>
<span id="cb97-9"><a href="#cb97-9" tabindex="-1"></a>  <span class="fu">names</span>(M) <span class="ot">&lt;-</span> <span class="fu">paste</span>(levs[<span class="dv">1</span><span class="sc">:</span>(<span class="fu">length</span>(levs)<span class="sc">-</span><span class="dv">1</span>)],<span class="st">&quot;vs subsequent&quot;</span>)</span>
<span id="cb97-10"><a href="#cb97-10" tabindex="-1"></a>  <span class="fu">attr</span>(M, <span class="st">&quot;desc&quot;</span>) <span class="ot">&lt;-</span> <span class="st">&quot;Helmert contrasts&quot;</span></span>
<span id="cb97-11"><a href="#cb97-11" tabindex="-1"></a>  M</span>
<span id="cb97-12"><a href="#cb97-12" tabindex="-1"></a>}</span>
<span id="cb97-13"><a href="#cb97-13" tabindex="-1"></a><span class="fu">helmert.emmc</span>(<span class="fu">levels</span>(dat<span class="sc">$</span>Group))</span></code></pre></div>
<pre><code>##   1 vs subsequent            2 vs subsequent
## 1       1.0000000 -0.00000000000000006343273
## 2      -0.3333333  1.00000000000000000000000
## 3      -0.3333333 -0.50000000000000011102230
## 4      -0.3333333 -0.50000000000000011102230
##             3 vs subsequent
## 1 -0.0000000000000001098687
## 2 -0.0000000000000001256066
## 3  0.9999999999999995559108
## 4 -0.9999999999999997779554</code></pre>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" tabindex="-1"></a><span class="fu">contrast</span>(emm,<span class="st">&quot;helmert&quot;</span>,<span class="at">adjust=</span><span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<pre><code>##  contrast             estimate     SE  df
##  Group1 vs subsequent   -0.196 0.0896 166
##  Group2 vs subsequent   -0.443 0.1010 166
##  Group3 vs subsequent   -0.200 0.1080 166
##  t.ratio p.value
##   -2.183  0.0305
##   -4.402  &lt;.0001
##   -1.853  0.0657</code></pre>
<p>and we get the contrast estimates as expected. For the
<code>difference</code> contrast we can use
<code>con_weights&lt;-contr.helmert(n)</code> in the function and we get
the correct codes.</p>
</div>
</div>
<div id="rosettas-files" class="section level1 adm adm-seealso">
<h1>Rosetta’s files</h1>
<ul>
<li>
<a href="./rosetta_contrasts.html">Rosetta store: contrasts</a>
</li>
<li>
<a href="./rosetta_simpleint.html">Simple Effects and Simple
Interactions</a>
</li>
<li>
<a href="./rosetta_gzlmmixed1.html">Rosetta store: Generalized Mixed</a>
</li>
<li>
<a href="./rosetta_moderation.html">Rosetta store: moderation</a>
</li>
</ul>
</div>
<div id="comments" class="section level1 adm adm-warning">
<h1>Comments?</h1>
<p>
Got comments, issues or spotted a bug? Please open an issue on
<a href="https://github.com/gamlj/gamlj//issues " target="_blank"> GAMLj
at github</a> or <a href="mailto:mcfanda@gmail.com

">send me an email</a>
</p>
</div>
</div>

   
   
            
      

  <script>
    $(document).ready(function () {

			
 		
		$('#content img:not(.no-lightbox)').addClass("image-lb");
	$('#content').magnificPopup({
	    type:'image',
	    closeOnContentClick: false,
	    closeBtnInside: false,
	    delegate: '.image-lb',
	    gallery: {enabled: false },
	    image: {
	        verticalFit: true,
		titleSrc: 'alt'
	    }
 	});
 	    });
  </script>



    <!-- dynamically load mathjax for compatibility with self-contained -->
  <script>
    (function () {
	var script = document.createElement("script");
	script.type = "text/javascript";
	script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
	document.getElementsByTagName("head")[0].appendChild(script);
    })();
  </script>
  
</body>
</html>
